
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: akv2k8s
spec:
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
    - ALL
  volumes:
    - 'secret'
    - 'hostPath'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  readOnlyRootFilesystem: false
  # Allowing pods to use Azure
  allowedHostPaths:
    - pathPrefix: "/etc/kubernetes/azure.json"
      readOnly: true # only allow read-only mounts 
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: psp:akv2k8s
  namespace: admin
rules:
- apiGroups: ['extensions']
  resources: ['podsecuritypolicies']
  resourceNames: ['akv2k8s']
  verbs: ['use']
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: akv2k8s:psp:readazure
  namespace: admin
subjects:
- kind: ServiceAccount
  name: akv2k8s-kvcontroller-azure-key-vault-controller
  namespace: admin
roleRef:
  kind: Role
  name: psp:akv2k8s
  apiGroup: rbac.authorization.k8s.io
