variable "key_vault_id" {}
variable "location" {}
variable resource_group_name {}
variable "log_analytics_workspace_id" {}
variable "log_analytics_workspace_key" {}
variable "grafana_admin_password" {}
variable "storage_account_name" {}
variable "storage_account_key" {}
variable "share_name" {}
variable "aci_network_profile_id" {}
variable "acr_name" {}